Add support for RISC-V cores of pico2

diff --git a/utils/pico_sdk b/utils/pico_sdk
--- a/utils/pico_sdk
+++ b/utils/pico_sdk
@@ -11,6 +11,27 @@ if [[ $USER != "root" ]]; then
     exit 1
 fi
 
+install_riscv=0
+usage="Usage: $0 [--riscv|-v] [--help|-h]"
+while [[ $# -gt 0 ]]; do
+    case $1 in
+    -r|--riscv)
+        install_riscv=1
+        shift
+        ;;
+    -h|--help)
+        echo "$usage"
+        echo "  -r|--riscv -- Additionally install RISC-V tool chain"
+        echo "  -h|--help   -- Display this help message"
+        exit 0
+        ;;
+    *)
+        echo "!Error: Unknown argument: $1"
+        echo $usage
+        exit 1
+    esac
+done
+
 mkdir -p /usr/src
 
 # get latest list of available tools
@@ -19,10 +40,10 @@ apt update
 # install helpful tools
 apt-get install -y picocom tmux
 
-# install arm toolchain dependencies
+# install ARM toolchain dependencies
 apt-get install -y build-essential curl
 
-# install ARM Toolchain
+# install ARM toolchain
 cd /usr/src
 arm_url="https://developer.arm.com"
 version=$(curl -s ${arm_url}/downloads/-/arm-gnu-toolchain-downloads |\
@@ -30,9 +51,36 @@ version=$(curl -s ${arm_url}/downloads/-/arm-gnu-toolchain-downloads |\
 toolchain_url="${arm_url}/-/media/Files/downloads/gnu"
 toolchain_url+="/${version}/binrel/arm-gnu-toolchain"
 toolchain_url+="-${version}-x86_64-arm-none-eabi.tar.xz"
+arm_install_dir=/opt/gcc-arm-none-eabi
 curl -Lo gcc-arm-none-eabi.tar.xz $toolchain_url
-mkdir -p /opt/gcc-arm-none-eabi
-tar xf gcc-arm-none-eabi.tar.xz --strip-components=1 -C /opt/gcc-arm-none-eabi
+mkdir -p $arm_install_dir
+tar xf gcc-arm-none-eabi.tar.xz --strip-components=1 -C $arm_install_dir
+
+if [[ $install_riscv -eq 1 ]]; then
+    # install RISC-V toolchain dependencies
+    apt-get install -y autoconf automake autotools-dev curl \
+                       python3 python3-pip libmpc-dev \
+                       libmpfr-dev libgmp-dev gawk build-essential \
+                       bison flex texinfo gperf libtool \
+                       patchutils bc zlib1g-dev libexpat-dev \
+                       ninja-build git cmake libglib2.0-dev libslirp-dev
+
+    # install RISC-V toolchain
+    riscv_install_dir=/opt/gcc-riscv32-unknown-elf
+    mkdir -p $riscv_install_dir
+    cd /usr/src
+    git clone https://github.com/riscv/riscv-gnu-toolchain
+    cd riscv-gnu-toolchain
+    git clone https://github.com/gcc-mirror/gcc gcc-14 -b releases/gcc-14
+    multilib="rv32ima_zicsr_zifencei_zba_zbb_zbs_zbkb_zca_zcb-ilp32--"
+    multilib=$multilib";rv32imac_zicsr_zifencei_zba_zbb_zbs_zbkb-ilp32--"
+    ./configure --prefix=$riscv_install_dir \
+        --with-arch=rv32ima_zicsr_zifencei_zba_zbb_zbs_zbkb_zca_zcb \
+        --with-abi=ilp32 \
+        --with-multilib-generator=$multilib \
+        --with-gcc-src=`pwd`/gcc-14
+    make -j$(nproc)
+fi
 
 # install raspberry pi pico SDK dependencies
 apt-get install -y git
@@ -67,5 +115,9 @@ apt update && apt-get install -y python3
 
 echo "Remember to:"
 echo "    install and use usbipd in Windows to enable use of USB devices in WSL"
-echo "    export PATH=\$PATH:/opt/gcc-arm-none-eabi/bin"
+if [[ $install_riscv -eq 1 ]]; then
+    echo "    export PATH=\$PATH:$arm_install_dir/bin:$riscv_install_dir/bin"
+else
+    echo "    export PATH=\$PATH:$arm_install_dir/bin"
+fi
 echo "    export PICO_SDK_PATH=/opt/pico-sdk"
